HOST: 'localhost'
APP_PORT: '9123'

DB_NAME: 'wapp_dev'
DB_HOST: 'localhost'
DB_USER: 'postgres'
DB_PASSWORD: ''
DB_PORT: '5000'

W_EMAIL_USERNAME: 'w.run.training@gmail.com'
W_EMAIL_PASSWORD: '%6@mK9U2!uXb'
COACH_EMAIL_ADDRESS: 'chuayewwee@gmail.com'